# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_design2 <- function(nx, ncoef, ord, temp) {
    .Call('_quickns_make_design2', PACKAGE = 'quickns', nx, ncoef, ord, temp)
}

make_design_no_intcpt_cpp <- function(nx, ncoef, ord, temp) {
    .Call('_quickns_make_design_no_intcpt_cpp', PACKAGE = 'quickns', nx, ncoef, ord, temp)
}

get_basis <- function(const_m, basis_m) {
    .Call('_quickns_get_basis', PACKAGE = 'quickns', const_m, basis_m)
}

